name: tontine_v2
description: "Tontine grass field app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.8

environment:
  sdk: ^3.5.3

dependencies:
  cookie_jar: ^4.0.8
  file_picker: ^10.3.2
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_quill: ^11.4.2
  get_storage: ^2.1.1
  http: ^1.2.2
  http_interceptor: ^2.0.0
  http_parser: ^4.1.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  logging: ^1.3.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  share_plus: ^10.0.2
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/calebasse2.png"
  adaptive_icon_background: "#42a5f5"
  adaptive_icon_foreground: "assets/images/calebasse2.png"