name: tontine_v2
description: "Tontine grass field app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cookie_jar: ^4.0.8
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_quill: ^10.8.5
  get_storage: ^2.1.1
  http: ^1.2.2
  http_interceptor: ^2.0.0
  http_parser: ^4.1.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  logging: ^1.3.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env